import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Container, Theme } from "@radix-ui/themes";
import NavBar from "./NavBar";

import css from "./MainLayout.module.css";

const inter = Inter({
	subsets: ["latin"],
	variable: "--font-inter",
});

export const metadata: Metadata = {
	title: "Issue tracker",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.variable}>
				<Theme appearance="light" accentColor="violet">
					<NavBar />
					<main className={css.main}>
						<Container>{children}</Container>
					</main>
				</Theme>
			</body>
		</html>
	);
}
